name: Express.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on:
      - self-hosted
      - windows
      - x64
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.1
          cache: 'pnpm'
          
      - name: Install dependencies
        shell: cmd
        run: pnpm install

      - name: Install PM2 globally
        shell: cmd
        run: pnpm add -g pm2

      - name: Manage PM2 process
        shell: cmd
        run: |
          pm2 delete express-app || true
          pm2 start index.js --name express-app
