name: Express.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: windows-latest  

    steps:
    - name: Repository'yi Kontrol Et 
      uses: actions/checkout@v3

    - name: Node.js Kurulumu 
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Bağımlılıkları Yükle 
      run: npm install

    - name: Commit Detayları 
      shell: pwsh  
      run: |
        echo "İşlem Tarihi: 2025-01-23 17:33:01"
        echo "Kullanıcı: BerkcanYuzer"
        echo "Commit Hash: ${{ github.sha }}"
        echo "Branch: ${{ github.ref }}"

    - name: Dosya Yapısını Kontrol Et 
      shell: pwsh   
      run: |
        echo " Proje Yapısı:"
        dir
        echo " index.js Kontrolü:"
        if (Test-Path "index.js") {
            echo " index.js mevcut"
        } else {
            echo " index.js bulunamadı"
            exit 1
        }